// Common action types
export const SET_LOADING = 'SET_LOADING';
export const SET_SIDEBAR_OPEN = 'SET_SIDEBAR_OPEN';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

// Auth action types
export const AUTH = {
  LOGIN_REQUEST: "AUTH.LOGIN_REQUEST",
  LOGIN_SUCCESS: "AUTH.LOGIN_SUCCESS",
  LOGIN_FAILURE: "AUTH.LOGIN_FAILURE",

  LOGOUT: "AUTH.LOGOUT",
  LOGOUT_SUCCESS: "AUTH.LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "AUTH.LOGOUT_FAILURE",

  SET_LOADING: "AUTH.SET_LOADING",
};



// Category action types
export const CATEGORY = {
  GET_ALL: 'CATEGORY/GET_ALL',
  SET_ALL: 'CATEGORY/SET_ALL',
  GET_BY_ID: 'CATEGORY/GET_BY_ID',
  SET_ONE: 'CATEGORY/SET_ONE',
  CREATE: 'CATEGORY/CREATE',
  CREATE_SUCCESS: 'CATEGORY/CREATE_SUCCESS',
  CREATE_FAILURE: 'CATEGORY/CREATE_FAILURE',
  UPDATE: 'CATEGORY/UPDATE',
  UPDATE_SUCCESS: 'CATEGORY/UPDATE_SUCCESS',
  UPDATE_FAILURE: 'CATEGORY/UPDATE_FAILURE',
  UPDATE_STATUS: 'CATEGORY/UPDATE_STATUS',
  UPDATE_STATUS_SUCCESS: 'CATEGORY/UPDATE_STATUS_SUCCESS',
  UPDATE_STATUS_FAILURE: 'CATEGORY/UPDATE_STATUS_FAILURE',
  DELETE: 'CATEGORY/DELETE',
  DELETE_MANY: 'CATEGORY/DELETE_MANY',
  DELETE_SUCCESS: 'CATEGORY/DELETE_SUCCESS',
  DELETE_FAILURE: 'CATEGORY/DELETE_FAILURE',
  SET_LOADING: 'CATEGORY/SET_LOADING'
};


// Author action types
export const AUTHOR = {
  GET_ALL: 'AUTHOR/GET_ALL',
  SET_ALL: 'AUTHOR/SET_ALL',
  GET_BY_ID: 'AUTHOR/GET_BY_ID',
  SET_ONE: 'AUTHOR/SET_ONE',
  CREATE: 'AUTHOR/CREATE',
  CREATE_SUCCESS: 'AUTHOR/CREATE_SUCCESS',
  CREATE_FAILURE: 'AUTHOR/CREATE_FAILURE',
  UPDATE: 'AUTHOR/UPDATE',
  UPDATE_SUCCESS: 'AUTHOR/UPDATE_SUCCESS',
  UPDATE_FAILURE: 'AUTHOR/UPDATE_FAILURE',
  DELETE: 'AUTHOR/DELETE',
  DELETE_MANY: 'AUTHOR/DELETE_MANY',
  DELETE_SUCCESS: 'AUTHOR/DELETE_SUCCESS',
  DELETE_FAILURE: 'AUTHOR/DELETE_FAILURE',
  SET_LOADING: 'AUTHOR/SET_LOADING',
  UPDATE_STATUS: 'AUTHOR/UPDATE_STATUS',
  UPDATE_STATUS_SUCCESS: 'AUTHOR/UPDATE_STATUS_SUCCESS',
  UPDATE_STATUS_FAILURE: 'AUTHOR/UPDATE_STATUS_FAILURE',
};


// Dashboard action types
export const DASHBOARD = {
  GET: 'DASHBOARD/GET',
  SET_DATA: 'DASHBOARD/SET_DATA',
  SET_LOADING: 'DASHBOARD/SET_LOADING',
  TOGGLE_SIDEBAR: 'DASHBOARD/TOGGLE_SIDEBAR'
}; 