// Common action types
export const SET_LOADING = 'SET_LOADING';
export const SET_SIDEBAR_OPEN = 'SET_SIDEBAR_OPEN';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

// Auth action types
export const AUTH = {
  LOGIN_REQUEST: "AUTH.LOGIN_REQUEST",
  LOGIN_SUCCESS: "AUTH.LOGIN_SUCCESS",
  LOGIN_FAILURE: "AUTH.LOGIN_FAILURE",

  LOGOUT: "AUTH.LOGOUT",
  LOGOUT_SUCCESS: "AUTH.LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "AUTH.LOGOUT_FAILURE",

  SET_LOADING: "AUTH.SET_LOADING",
};



// Category action types
export const CATEGORY = {
  GET_ALL: 'CATEGORY/GET_ALL',
  SET_ALL: 'CATEGORY/SET_ALL',
  GET_BY_ID: 'CATEGORY/GET_BY_ID',
  SET_ONE: 'CATEGORY/SET_ONE',
  CREATE: 'CATEGORY/CREATE',
  CREATE_SUCCESS: 'CATEGORY/CREATE_SUCCESS',
  CREATE_FAILURE: 'CATEGORY/CREATE_FAILURE',
  UPDATE: 'CATEGORY/UPDATE',
  UPDATE_SUCCESS: 'CATEGORY/UPDATE_SUCCESS',
  UPDATE_FAILURE: 'CATEGORY/UPDATE_FAILURE',
  DELETE: 'CATEGORY/DELETE',
  DELETE_MANY: 'CATEGORY/DELETE_MANY',
  DELETE_SUCCESS: 'CATEGORY/DELETE_SUCCESS',
  DELETE_FAILURE: 'CATEGORY/DELETE_FAILURE',
  SET_LOADING: 'CATEGORY/SET_LOADING'
};

// User action types
export const USER = {
  GET_ALL: 'USER/GET_ALL',
  SET_ALL: 'USER/SET_ALL',
  GET_BY_ID: 'USER/GET_BY_ID',
  SET_ONE: 'USER/SET_ONE',
  CREATE: 'USER/CREATE',
  CREATE_SUCCESS: 'USER/CREATE_SUCCESS',
  CREATE_FAILURE: 'USER/CREATE_FAILURE',
  UPDATE: 'USER/UPDATE',
  UPDATE_SUCCESS: 'USER/UPDATE_SUCCESS',
  UPDATE_FAILURE: 'USER/UPDATE_FAILURE',
  DELETE: 'USER/DELETE',
  DELETE_MANY: 'USER/DELETE_MANY',
  DELETE_SUCCESS: 'USER/DELETE_SUCCESS',
  DELETE_FAILURE: 'USER/DELETE_FAILURE',
  SET_LOADING: 'USER/SET_LOADING'
};

// Dashboard action types
export const DASHBOARD = {
  GET: 'DASHBOARD/GET',
  SET_DATA: 'DASHBOARD/SET_DATA',
  SET_LOADING: 'DASHBOARD/SET_LOADING',
  TOGGLE_SIDEBAR: 'DASHBOARD/TOGGLE_SIDEBAR'
}; 